- name: restrict-grafana-alloy
  match: grafana-alloy
  allow:
    - namespace: tool-cluebotng-monitoring

- name: restrict-monitoring-toolforge
  match: monitoring-toolforge
  allow:
    - pod: grafana-alloy
