# Core tools
- name: restrict-prometheus
  match: prometheus
  allow:
    # Internal access
    - pod: grafana
    - pod: grafana-alloy

    # Namespaces which use remote write
    - namespace: tool-cluebot-syncer
    - namespace: tool-cluebot3
    - namespace: tool-cluebotng
    - namespace: tool-cluebotng-editsets
    - namespace: tool-cluebotng-review
    - namespace: tool-cluebotng-staging
    - namespace: tool-cluebotng-trainer
    - namespace: tool-toolforge-functional-runner

- name: restrict-alertmanager
  match: alertmanager
  allow:
    # Internal access
    - pod: prometheus
    - pod: grafana

# Alertmanager web hooks
- name: restrict-wiki-update-receiver
  match: wiki-update-receiver
  allow:
    # Internal access
    - name: alertmanager

# Exporters
- name: restrict-blackbox-exporter
  match: blackbox-exporter
  allow:
    # Internal access
    - name: prometheus

- name: restrict-checker
  match: checker
  allow:
    # Internal access
    - name: prometheus

- name: restrict-grafana-alloy
  match: grafana-alloy
  allow:
    - namespace: tool-cluebotng-monitoring

- name: restrict-monitoring-toolforge
  match: monitoring-toolforge
  allow:
    - pod: grafana-alloy
