name: Setup
on: { push: { branches: [ 'main' ] } }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cluebotng/ci-execute-fabric@main
        with:
          task: setup
          ssh_key: ${{ secrets.CI_SSH_KEY }}
